language: objective-c
osx_image: xcode10.1

branches:
  only:
  - master

env:
  global:
  - NODE_VERSION=11.9.0

export PING_SLEEP=30s
export WORKDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BUILD_OUTPUT=$WORKDIR/build.out
touch $BUILD_OUTPUT

# dump_mvn_output() {
#    echo Tailing the last 500 lines of mvn output:
#    tail -500 $BUILD_OUTPUT 
# }

install:
- brew install yarn
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g react-native-cli
- rm -rf ~/.rncache
- rm -rf ios/build
- rm -rf node_modules
- yarn install
- cd node_modules/react-native && ./scripts/ios-install-third-party.sh
- cd third-party/glog-0.3.4/ && ../../scripts/ios-configure-glog.sh
- cd ../../../../
# - dump_mvn_output
- cd ios && pod update && cd ..
# - dump_mvn_output
- detox build -c ios.sim.debug >> $BUILD_OUTPUT